title: I Love Krasne
email: kontakt@ilovekrasne.pl
description: >-
  Koszulki z nadrukiem "I ❤️ [miejscowość]" – idealne na TikToka.
baseurl: "/strona" 
url: "" 
theme: minima
plugins:
  - jekyll-feed
